  
FROM python:3.8

RUN mkdir /app
EXPOSE 8000
WORKDIR /app

RUN apt update && \
    apt install -y postgresql-client

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .